/* BASE ÚNICA — Boletim Sell Out | Hypera Pharma
 * Grão: bu × marca × rede — agregado a partir da base diária (dia × bu × marca × sku × canal × cliente).
 * marca = "TOTAL" -> linha agregada da BU · "DEMAIS" -> marcas fora do top 5 · rede = "TOTAL" -> soma dos canais.
 * bu: TOTAL | CH | PP | SC | SG | VITNQ | (linhas auxiliares da tabela de BUs).
 * Valores em R$ milhões (PX); cresc/vd/vi em %. null = não informado no boletim.
 * forecast = orçamento reprojetado no ciclo (rolling forecast) — no arquivo de exemplo vem estimado
 * como a média entre orçamento e projeção atual; a extração real substitui pela coluna FORECAST.
 * 536 linhas de fato · fonte: Dados IQVIA | Base MDTR Diário · corte 15/08/26 (10 dias úteis).
 */
window.BASE_BOLETIM = {
  META: {"titulo":"Boletim Sell Out","subtitulo":"Resumo Executivo","referencia":"Agosto/26","dataCorte":"15/08/26","diasUteis":10,"diasUteisAA":11,"fonte":"Dados IQVIA | Base MDTR Diário","atualizadoEm":"15/ago/26","moeda":"R$ milhões (PX)","mtd":{"aa":{"vd":181.4,"vi":179.7,"total":361.1},"atual":{"vd":189.8,"vi":187.3,"total":377},"cresc":4.4},"mes":{"aa":{"vd":363.4,"vi":395.4,"total":758.8},"proj":{"vd":378,"vi":435,"total":813},"cresc":7.1,"cresVD":4,"cresVI":10},"destaques":[["TAMARINE",15.6],["ENGOV",9.3],["LISADOR",17.3],["DRAMIN",5.5],["PIELUS FORTE",130],["NOUVE",24.7],["DIPIRONA SODICA MG",45.8],["FLAVONID",23.2]],"consideracoes":"A projeção Total Hypera para agosto é 7,1% com seguintes destaques: Vitaminas Total SG — a projeção de VIT NQ é de R$ 13,8 milhões com crescimento de 8,0%. VI: representando 52,5% do total de vendas, alcançará R$ 7,3 milhões, refletindo uma queda de -17,1%. VD: com um aumento de 62,1%, contribuirá com R$ 6,6 milhões para o total.","curva":{"ano":2026,"mes":8,"diasMes":31,"diaAtual":15,"real":[22,37.2,65.9,94,121.5,148.5,178.6,200.4,215.5,243.8,271.7,298.9,325.6,355.4,377],"proj":[393.4,424.2,454.4,484,517,549.4,572.9,589,619.6,649.5,678.7,711.4,743.5,766.8,782.8,813],"aa":[21.6,36.5,64.6,92.1,119.1,145.5,174.9,196.3,211.1,238.9,266.1,292.8,318.9,348.1,369.3,383.9,411.5,438.4,464.8,494.3,523.2,544.2,558.7,585.9,612.6,638.7,667.9,696.5,717.3,731.6,758.6],"orcTotal":826.5},"links":{"hub":"https://app.powerbi.com/groups/ddd0da03-c7aa-4718-a584-f15ad9913600/reports/534124f0-a9c2-4444-88c0-1cca50d91f2c/ReportSection?experience=power-bi","executivos":"https://app.powerbi.com/groups/me/apps/1db230f5-dd67-4f96-aac1-10967036ac8b/reports/93571e31-2150-4eac-96c0-46c66e3d270b/2e9a45f7eae5ed53481a?ctid=3f7a3df4-f85b-4ca8-98d0-08b1034e6567&experience=power-bi","deck":"boletim-sell-out.dc.html","pdf":"boletim-sell-out.dc.html"},"assinatura":{"nome":"Renata Martins","area":"Hypera Pharma - Unidade Cidade Jardim","email":"renata.martins@hypera.com.br"}},
  COLUNAS: ["bu","marca","rede","realAA","real","proj","projIni","orcAbs","cresc","vd","vi","pProj","pIni","pOrc","forecast"],
  FATOS: [
    ["CH","TOTAL","TOTAL",216.5,98.7,220,221.3,229.7,null,43.8,56.2,1.6,2.2,6,224.9],
    ["PP","TOTAL","TOTAL",253.8,127.9,270.5,269.1,273,null,57.2,42.8,6.6,6,7.6,271.8],
    ["SC","TOTAL","TOTAL",61.7,34.5,71.6,71.6,71.2,null,83.2,16.8,16,16,15.5,71.4],
    ["SG","TOTAL","TOTAL",237.7,121.6,263.1,259.8,264.7,null,26.8,73.2,10.7,9.6,11.7,263.9],
    ["COBERTURA","TOTAL","TOTAL",10.9,5.6,12.1,11.9,12.2,10.7,null,null,10.7,9.6,11.7,12.1],
    ["SG - GENÉRICOS","TOTAL","TOTAL",105.6,57,123.7,123.1,118.4,17.1,27.2,72.8,17.1,17.3,13,121.1],
    ["SG - SIMILARES","TOTAL","TOTAL",121.1,58.9,127.3,124.7,134.1,5.1,26.4,73.6,5.1,2.9,10.5,130.7],
    ["SMART (EX-VIT)","TOTAL","TOTAL",108.4,52.4,113.5,111.4,120.2,4.7,23.9,76.1,4.7,2.8,10.4,116.9],
    ["VIT NEO QUÍMICA","TOTAL","TOTAL",12.8,6.6,13.8,13.3,13.9,8,47.6,52.4,8,4.1,11.6,13.9],
    ["Total","TOTAL","TOTAL",769.8,382.6,825.1,821.8,838.7,7.2,45.8,54.2,7.2,6.8,9,831.9],
    ["Total s/ Cobertura","TOTAL","TOTAL",758.8,377,813,809.8,826.5,7.1,46.5,53.5,7.1,6.8,9,819.8],
    ["TOTAL","TOTAL","DROGASIL",74.9,39.7,76.3,null,null,6.2,null,null,2,null,null,null],
    ["CH","TOTAL","DROGASIL",null,null,null,null,null,-0.3,null,null,null,null,null,null],
    ["PP","TOTAL","DROGASIL",null,null,null,null,null,-2,null,null,null,null,null,null],
    ["SC","TOTAL","DROGASIL",null,null,null,null,null,-5.1,null,null,null,null,null,null],
    ["SG","TOTAL","DROGASIL",null,null,null,null,null,22.9,null,null,null,null,null,null],
    ["TOTAL","TOTAL","DELIVERY",35.7,22.9,47,null,null,28.5,null,null,31.8,null,null,null],
    ["CH","TOTAL","DELIVERY",null,null,null,null,null,6.6,null,null,null,null,null,null],
    ["PP","TOTAL","DELIVERY",null,null,null,null,null,21.4,null,null,null,null,null,null],
    ["SC","TOTAL","DELIVERY",null,null,null,null,null,48.3,null,null,null,null,null,null],
    ["SG","TOTAL","DELIVERY",null,null,null,null,null,52,null,null,null,null,null,null],
    ["TOTAL","TOTAL","PAGUE MENOS",39.9,20.4,39.1,null,null,2.4,null,null,-1.8,null,null,null],
    ["CH","TOTAL","PAGUE MENOS",null,null,null,null,null,-12.1,null,null,null,null,null,null],
    ["PP","TOTAL","PAGUE MENOS",null,null,null,null,null,-5.9,null,null,null,null,null,null],
    ["SC","TOTAL","PAGUE MENOS",null,null,null,null,null,22.8,null,null,null,null,null,null],
    ["SG","TOTAL","PAGUE MENOS",null,null,null,null,null,8.8,null,null,null,null,null,null],
    ["TOTAL","TOTAL","DROGARIA SAO PAULO",38.2,18.7,35.9,null,null,-2.1,null,null,-6,null,null,null],
    ["CH","TOTAL","DROGARIA SAO PAULO",null,null,null,null,null,-13,null,null,null,null,null,null],
    ["PP","TOTAL","DROGARIA SAO PAULO",null,null,null,null,null,-4.6,null,null,null,null,null,null],
    ["SC","TOTAL","DROGARIA SAO PAULO",null,null,null,null,null,6.3,null,null,null,null,null,null],
    ["SG","TOTAL","DROGARIA SAO PAULO",null,null,null,null,null,-5.9,null,null,null,null,null,null],
    ["TOTAL","TOTAL","RAIA",35.4,17.1,32.9,null,null,-3.3,null,null,-7.1,null,null,null],
    ["CH","TOTAL","RAIA",null,null,null,null,null,-9.8,null,null,null,null,null,null],
    ["PP","TOTAL","RAIA",null,null,null,null,null,-10.9,null,null,null,null,null,null],
    ["SC","TOTAL","RAIA",null,null,null,null,null,-10.8,null,null,null,null,null,null],
    ["SG","TOTAL","RAIA",null,null,null,null,null,13,null,null,null,null,null,null],
    ["TOTAL","TOTAL","SAO JOAO",18.3,9.5,21.4,null,null,3.3,null,null,16.4,null,null,null],
    ["CH","TOTAL","SAO JOAO",null,null,null,null,null,12.5,null,null,null,null,null,null],
    ["PP","TOTAL","SAO JOAO",null,null,null,null,null,13.1,null,null,null,null,null,null],
    ["SC","TOTAL","SAO JOAO",null,null,null,null,null,27.6,null,null,null,null,null,null],
    ["SG","TOTAL","SAO JOAO",null,null,null,null,null,38.2,null,null,null,null,null,null],
    ["TOTAL","TOTAL","PANVEL",17.2,9.2,17.8,null,null,7.7,null,null,3.7,null,null,null],
    ["CH","TOTAL","PANVEL",null,null,null,null,null,-4.3,null,null,null,null,null,null],
    ["PP","TOTAL","PANVEL",null,null,null,null,null,3.1,null,null,null,null,null,null],
    ["SC","TOTAL","PANVEL",null,null,null,null,null,7.1,null,null,null,null,null,null],
    ["SG","TOTAL","PANVEL",null,null,null,null,null,11.1,null,null,null,null,null,null],
    ["TOTAL","TOTAL","PACHECO",15.7,7.4,14.3,null,null,-5,null,null,-8.8,null,null,null],
    ["CH","TOTAL","PACHECO",null,null,null,null,null,-14.8,null,null,null,null,null,null],
    ["PP","TOTAL","PACHECO",null,null,null,null,null,-5,null,null,null,null,null,null],
    ["SC","TOTAL","PACHECO",null,null,null,null,null,-3.9,null,null,null,null,null,null],
    ["SG","TOTAL","PACHECO",null,null,null,null,null,-11,null,null,null,null,null,null],
    ["TOTAL","TOTAL","DROGAL",10.9,5.8,13.1,null,null,6.6,null,null,19.8,null,null,null],
    ["CH","TOTAL","DROGAL",null,null,null,null,null,12.5,null,null,null,null,null,null],
    ["PP","TOTAL","DROGAL",null,null,null,null,null,17.5,null,null,null,null,null,null],
    ["SC","TOTAL","DROGAL",null,null,null,null,null,19,null,null,null,null,null,null],
    ["SG","TOTAL","DROGAL",null,null,null,null,null,37.7,null,null,null,null,null,null],
    ["TOTAL","TOTAL","ARAUJO",11,5.8,11.2,null,null,6.2,null,null,2,null,null,null],
    ["CH","TOTAL","ARAUJO",null,null,null,null,null,-6.2,null,null,null,null,null,null],
    ["PP","TOTAL","ARAUJO",null,null,null,null,null,-1,null,null,null,null,null,null],
    ["SC","TOTAL","ARAUJO",null,null,null,null,null,11,null,null,null,null,null,null],
    ["SG","TOTAL","ARAUJO",null,null,null,null,null,10.3,null,null,null,null,null,null],
    ["TOTAL","TOTAL","OUTROS",66.2,33.3,68.9,null,null,0.7,null,null,4,null,null,null],
    ["CH","TOTAL","OUTROS",null,null,null,null,null,1.5,null,null,null,null,null,null],
    ["PP","TOTAL","OUTROS",null,null,null,null,null,3.2,null,null,null,null,null,null],
    ["SC","TOTAL","OUTROS",null,null,null,null,null,18.4,null,null,null,null,null,null],
    ["SG","TOTAL","OUTROS",null,null,null,null,null,2.6,null,null,null,null,null,null],
    ["TOTAL","TOTAL","VD",363.4,189.8,378,null,null,4.6,null,null,4,null,null,null],
    ["CH","TOTAL","VD",null,null,null,null,null,-2.9,null,null,null,null,null,null],
    ["PP","TOTAL","VD",null,null,null,null,null,0.7,null,null,null,null,null,null],
    ["SC","TOTAL","VD",null,null,null,null,null,16,null,null,null,null,null,null],
    ["SG","TOTAL","VD",null,null,null,null,null,13.7,null,null,null,null,null,null],
    ["TOTAL","TOTAL","VI",395.4,187.3,435,null,null,4.2,null,null,10,null,null,null],
    ["CH","TOTAL","VI",null,null,null,null,null,5.4,null,null,null,null,null,null],
    ["PP","TOTAL","VI",null,null,null,null,null,15.5,null,null,null,null,null,null],
    ["SC","TOTAL","VI",null,null,null,null,null,16,null,null,null,null,null,null],
    ["SG","TOTAL","VI",null,null,null,null,null,9.6,null,null,null,null,null,null],
    ["TOTAL","TOTAL","TOTAL",758.8,377,813,null,null,4.4,null,null,7.1,null,null,null],
    ["CH","TOTAL PB","TOTAL",216.5,98.7,220,null,null,-4.2,43.8,56.2,1.6,null,null,null],
    ["PP","TOTAL PB","TOTAL",253.8,127.9,270.5,null,null,5.9,57.2,42.8,6.6,null,null,null],
    ["SC","TOTAL PB","TOTAL",61.7,34.5,71.6,null,null,17.4,83.2,16.8,16,null,null,null],
    ["SG","TOTAL PB","TOTAL",226.7,116,251,null,null,7.5,26.8,73.2,10.7,null,null,null],
    ["CH","BUSCOPAN","DROGASIL",null,null,null,null,null,-1.9,null,null,null,null,null,null],
    ["CH","NEOSALDINA","DROGASIL",null,null,null,null,null,0.3,null,null,null,null,null,null],
    ["CH","BENEGRIP","DROGASIL",null,null,null,null,null,-17.6,null,null,null,null,null,null],
    ["CH","TAMARINE","DROGASIL",null,null,null,null,null,10,null,null,null,null,null,null],
    ["CH","EPOCLER","DROGASIL",null,null,null,null,null,4,null,null,null,null,null,null],
    ["CH","CORISTINA","DROGASIL",null,null,null,null,null,-16.5,null,null,null,null,null,null],
    ["CH","ENGOV","DROGASIL",null,null,null,null,null,0,null,null,null,null,null,null],
    ["CH","BUSCOFEM","DROGASIL",null,null,null,null,null,-17.7,null,null,null,null,null,null],
    ["CH","BUSCOPAN","DELIVERY",null,null,null,null,null,3.9,null,null,null,null,null,null],
    ["CH","NEOSALDINA","DELIVERY",null,null,null,null,null,11.4,null,null,null,null,null,null],
    ["CH","BENEGRIP","DELIVERY",null,null,null,null,null,-27.8,null,null,null,null,null,null],
    ["CH","TAMARINE","DELIVERY",null,null,null,null,null,8,null,null,null,null,null,null],
    ["CH","EPOCLER","DELIVERY",null,null,null,null,null,1.7,null,null,null,null,null,null],
    ["CH","CORISTINA","DELIVERY",null,null,null,null,null,-19.8,null,null,null,null,null,null],
    ["CH","ENGOV","DELIVERY",null,null,null,null,null,-14.2,null,null,null,null,null,null],
    ["CH","BUSCOFEM","DELIVERY",null,null,null,null,null,1.3,null,null,null,null,null,null],
    ["CH","BUSCOPAN","PAGUE MENOS",null,null,null,null,null,-12,null,null,null,null,null,null],
    ["CH","NEOSALDINA","PAGUE MENOS",null,null,null,null,null,-11.7,null,null,null,null,null,null],
    ["CH","BENEGRIP","PAGUE MENOS",null,null,null,null,null,-35.6,null,null,null,null,null,null],
    ["CH","TAMARINE","PAGUE MENOS",null,null,null,null,null,2.3,null,null,null,null,null,null],
    ["CH","EPOCLER","PAGUE MENOS",null,null,null,null,null,4.4,null,null,null,null,null,null],
    ["CH","CORISTINA","PAGUE MENOS",null,null,null,null,null,-25.7,null,null,null,null,null,null],
    ["CH","ENGOV","PAGUE MENOS",null,null,null,null,null,-16.7,null,null,null,null,null,null],
    ["CH","BUSCOFEM","PAGUE MENOS",null,null,null,null,null,-9.8,null,null,null,null,null,null],
    ["CH","BUSCOPAN","DROGARIA SAO PAULO",null,null,null,null,null,-9,null,null,null,null,null,null],
    ["CH","NEOSALDINA","DROGARIA SAO PAULO",null,null,null,null,null,-7.7,null,null,null,null,null,null],
    ["CH","BENEGRIP","DROGARIA SAO PAULO",null,null,null,null,null,-35.7,null,null,null,null,null,null],
    ["CH","TAMARINE","DROGARIA SAO PAULO",null,null,null,null,null,-14.8,null,null,null,null,null,null],
    ["CH","EPOCLER","DROGARIA SAO PAULO",null,null,null,null,null,-8.8,null,null,null,null,null,null],
    ["CH","CORISTINA","DROGARIA SAO PAULO",null,null,null,null,null,-22.3,null,null,null,null,null,null],
    ["CH","ENGOV","DROGARIA SAO PAULO",null,null,null,null,null,-6.9,null,null,null,null,null,null],
    ["CH","BUSCOFEM","DROGARIA SAO PAULO",null,null,null,null,null,-13.3,null,null,null,null,null,null],
    ["CH","BUSCOPAN","RAIA",null,null,null,null,null,-12.8,null,null,null,null,null,null],
    ["CH","NEOSALDINA","RAIA",null,null,null,null,null,-7.3,null,null,null,null,null,null],
    ["CH","BENEGRIP","RAIA",null,null,null,null,null,-29.7,null,null,null,null,null,null],
    ["CH","TAMARINE","RAIA",null,null,null,null,null,3.2,null,null,null,null,null,null],
    ["CH","EPOCLER","RAIA",null,null,null,null,null,-6.8,null,null,null,null,null,null],
    ["CH","CORISTINA","RAIA",null,null,null,null,null,-26.2,null,null,null,null,null,null],
    ["CH","ENGOV","RAIA",null,null,null,null,null,-5.9,null,null,null,null,null,null],
    ["CH","BUSCOFEM","RAIA",null,null,null,null,null,-25.6,null,null,null,null,null,null],
    ["CH","BUSCOPAN","SAO JOAO",null,null,null,null,null,3.6,null,null,null,null,null,null],
    ["CH","NEOSALDINA","SAO JOAO",null,null,null,null,null,24.7,null,null,null,null,null,null],
    ["CH","BENEGRIP","SAO JOAO",null,null,null,null,null,-5.4,null,null,null,null,null,null],
    ["CH","TAMARINE","SAO JOAO",null,null,null,null,null,12.4,null,null,null,null,null,null],
    ["CH","EPOCLER","SAO JOAO",null,null,null,null,null,22,null,null,null,null,null,null],
    ["CH","CORISTINA","SAO JOAO",null,null,null,null,null,-7.9,null,null,null,null,null,null],
    ["CH","ENGOV","SAO JOAO",null,null,null,null,null,31.1,null,null,null,null,null,null],
    ["CH","BUSCOFEM","SAO JOAO",null,null,null,null,null,17.4,null,null,null,null,null,null],
    ["CH","BUSCOPAN","PANVEL",null,null,null,null,null,0.2,null,null,null,null,null,null],
    ["CH","NEOSALDINA","PANVEL",null,null,null,null,null,7.5,null,null,null,null,null,null],
    ["CH","BENEGRIP","PANVEL",null,null,null,null,null,-14.2,null,null,null,null,null,null],
    ["CH","TAMARINE","PANVEL",null,null,null,null,null,12.6,null,null,null,null,null,null],
    ["CH","EPOCLER","PANVEL",null,null,null,null,null,-10.6,null,null,null,null,null,null],
    ["CH","CORISTINA","PANVEL",null,null,null,null,null,-16.2,null,null,null,null,null,null],
    ["CH","ENGOV","PANVEL",null,null,null,null,null,-11.5,null,null,null,null,null,null],
    ["CH","BUSCOFEM","PANVEL",null,null,null,null,null,-8.3,null,null,null,null,null,null],
    ["CH","BUSCOPAN","PACHECO",null,null,null,null,null,-9.1,null,null,null,null,null,null],
    ["CH","NEOSALDINA","PACHECO",null,null,null,null,null,-11.3,null,null,null,null,null,null],
    ["CH","BENEGRIP","PACHECO",null,null,null,null,null,-33.7,null,null,null,null,null,null],
    ["CH","TAMARINE","PACHECO",null,null,null,null,null,-21.4,null,null,null,null,null,null],
    ["CH","EPOCLER","PACHECO",null,null,null,null,null,-3.8,null,null,null,null,null,null],
    ["CH","CORISTINA","PACHECO",null,null,null,null,null,-14.7,null,null,null,null,null,null],
    ["CH","ENGOV","PACHECO",null,null,null,null,null,-6.2,null,null,null,null,null,null],
    ["CH","BUSCOFEM","PACHECO",null,null,null,null,null,-18.5,null,null,null,null,null,null],
    ["CH","BUSCOPAN","DROGAL",null,null,null,null,null,10.5,null,null,null,null,null,null],
    ["CH","NEOSALDINA","DROGAL",null,null,null,null,null,33.9,null,null,null,null,null,null],
    ["CH","BENEGRIP","DROGAL",null,null,null,null,null,-27,null,null,null,null,null,null],
    ["CH","TAMARINE","DROGAL",null,null,null,null,null,25.4,null,null,null,null,null,null],
    ["CH","EPOCLER","DROGAL",null,null,null,null,null,33.6,null,null,null,null,null,null],
    ["CH","CORISTINA","DROGAL",null,null,null,null,null,-24.3,null,null,null,null,null,null],
    ["CH","ENGOV","DROGAL",null,null,null,null,null,32,null,null,null,null,null,null],
    ["CH","BUSCOFEM","DROGAL",null,null,null,null,null,9.7,null,null,null,null,null,null],
    ["CH","BUSCOPAN","ARAUJO",null,null,null,null,null,-6.4,null,null,null,null,null,null],
    ["CH","NEOSALDINA","ARAUJO",null,null,null,null,null,0.6,null,null,null,null,null,null],
    ["CH","BENEGRIP","ARAUJO",null,null,null,null,null,-37.4,null,null,null,null,null,null],
    ["CH","TAMARINE","ARAUJO",null,null,null,null,null,4.5,null,null,null,null,null,null],
    ["CH","EPOCLER","ARAUJO",null,null,null,null,null,4.4,null,null,null,null,null,null],
    ["CH","CORISTINA","ARAUJO",null,null,null,null,null,-19.8,null,null,null,null,null,null],
    ["CH","ENGOV","ARAUJO",null,null,null,null,null,-6.7,null,null,null,null,null,null],
    ["CH","BUSCOFEM","ARAUJO",null,null,null,null,null,13.6,null,null,null,null,null,null],
    ["CH","BUSCOPAN","VD",null,null,null,null,null,-3.3,null,null,null,null,null,null],
    ["CH","NEOSALDINA","VD",null,null,null,null,null,3.2,null,null,null,null,null,null],
    ["CH","BENEGRIP","VD",null,null,null,null,null,-24.9,null,null,null,null,null,null],
    ["CH","TAMARINE","VD",null,null,null,null,null,5.2,null,null,null,null,null,null],
    ["CH","EPOCLER","VD",null,null,null,null,null,2.8,null,null,null,null,null,null],
    ["CH","CORISTINA","VD",null,null,null,null,null,-18.6,null,null,null,null,null,null],
    ["CH","ENGOV","VD",null,null,null,null,null,-0.5,null,null,null,null,null,null],
    ["CH","BUSCOFEM","VD",null,null,null,null,null,-9,null,null,null,null,null,null],
    ["CH","BUSCOPAN","VI",null,null,null,null,null,10.7,null,null,null,null,null,null],
    ["CH","NEOSALDINA","VI",null,null,null,null,null,1.8,null,null,null,null,null,null],
    ["CH","BENEGRIP","VI",null,null,null,null,null,-18.5,null,null,null,null,null,null],
    ["CH","TAMARINE","VI",null,null,null,null,null,29.6,null,null,null,null,null,null],
    ["CH","EPOCLER","VI",null,null,null,null,null,14.9,null,null,null,null,null,null],
    ["CH","CORISTINA","VI",null,null,null,null,null,-25.4,null,null,null,null,null,null],
    ["CH","ENGOV","VI",null,null,null,null,null,15.5,null,null,null,null,null,null],
    ["CH","BUSCOFEM","VI",null,null,null,null,null,0.9,null,null,null,null,null,null],
    ["PP","ADDERA D3","DROGASIL",null,null,null,null,null,4.8,null,null,null,null,null,null],
    ["PP","NESINA","DROGASIL",null,null,null,null,null,-16,null,null,null,null,null,null],
    ["PP","DRAMIN","DROGASIL",null,null,null,null,null,-3.1,null,null,null,null,null,null],
    ["PP","RINOSORO","DROGASIL",null,null,null,null,null,-16.3,null,null,null,null,null,null],
    ["PP","LISADOR","DROGASIL",null,null,null,null,null,11.2,null,null,null,null,null,null],
    ["PP","PREDSIM","DROGASIL",null,null,null,null,null,-13.7,null,null,null,null,null,null],
    ["PP","ALIVIUM","DROGASIL",null,null,null,null,null,-20.1,null,null,null,null,null,null],
    ["PP","COLFLEX","DROGASIL",null,null,null,null,null,9.5,null,null,null,null,null,null],
    ["PP","ADDERA D3","DELIVERY",null,null,null,null,null,13.7,null,null,null,null,null,null],
    ["PP","NESINA","DELIVERY",null,null,null,null,null,-17.4,null,null,null,null,null,null],
    ["PP","DRAMIN","DELIVERY",null,null,null,null,null,8.8,null,null,null,null,null,null],
    ["PP","RINOSORO","DELIVERY",null,null,null,null,null,-12.9,null,null,null,null,null,null],
    ["PP","LISADOR","DELIVERY",null,null,null,null,null,16.9,null,null,null,null,null,null],
    ["PP","PREDSIM","DELIVERY",null,null,null,null,null,-3.7,null,null,null,null,null,null],
    ["PP","ALIVIUM","DELIVERY",null,null,null,null,null,-8.6,null,null,null,null,null,null],
    ["PP","COLFLEX","DELIVERY",null,null,null,null,null,87.2,null,null,null,null,null,null],
    ["PP","ADDERA D3","PAGUE MENOS",null,null,null,null,null,-10.3,null,null,null,null,null,null],
    ["PP","NESINA","PAGUE MENOS",null,null,null,null,null,-4.7,null,null,null,null,null,null],
    ["PP","DRAMIN","PAGUE MENOS",null,null,null,null,null,-11.2,null,null,null,null,null,null],
    ["PP","RINOSORO","PAGUE MENOS",null,null,null,null,null,-20.7,null,null,null,null,null,null],
    ["PP","LISADOR","PAGUE MENOS",null,null,null,null,null,-4,null,null,null,null,null,null],
    ["PP","PREDSIM","PAGUE MENOS",null,null,null,null,null,-19.3,null,null,null,null,null,null],
    ["PP","ALIVIUM","PAGUE MENOS",null,null,null,null,null,-11.1,null,null,null,null,null,null],
    ["PP","COLFLEX","PAGUE MENOS",null,null,null,null,null,-13.1,null,null,null,null,null,null],
    ["PP","ADDERA D3","DROGARIA SAO PAULO",null,null,null,null,null,-10.2,null,null,null,null,null,null],
    ["PP","NESINA","DROGARIA SAO PAULO",null,null,null,null,null,16.9,null,null,null,null,null,null],
    ["PP","DRAMIN","DROGARIA SAO PAULO",null,null,null,null,null,-13.8,null,null,null,null,null,null],
    ["PP","RINOSORO","DROGARIA SAO PAULO",null,null,null,null,null,-23.7,null,null,null,null,null,null],
    ["PP","LISADOR","DROGARIA SAO PAULO",null,null,null,null,null,-2.4,null,null,null,null,null,null],
    ["PP","PREDSIM","DROGARIA SAO PAULO",null,null,null,null,null,-17.2,null,null,null,null,null,null],
    ["PP","ALIVIUM","DROGARIA SAO PAULO",null,null,null,null,null,-21.6,null,null,null,null,null,null],
    ["PP","COLFLEX","DROGARIA SAO PAULO",null,null,null,null,null,12.6,null,null,null,null,null,null],
    ["PP","ADDERA D3","RAIA",null,null,null,null,null,-4.2,null,null,null,null,null,null],
    ["PP","NESINA","RAIA",null,null,null,null,null,-21.5,null,null,null,null,null,null],
    ["PP","DRAMIN","RAIA",null,null,null,null,null,-12.5,null,null,null,null,null,null],
    ["PP","RINOSORO","RAIA",null,null,null,null,null,-23.2,null,null,null,null,null,null],
    ["PP","LISADOR","RAIA",null,null,null,null,null,-1.2,null,null,null,null,null,null],
    ["PP","PREDSIM","RAIA",null,null,null,null,null,-20.9,null,null,null,null,null,null],
    ["PP","ALIVIUM","RAIA",null,null,null,null,null,-28.1,null,null,null,null,null,null],
    ["PP","COLFLEX","RAIA",null,null,null,null,null,-3,null,null,null,null,null,null],
    ["PP","ADDERA D3","SAO JOAO",null,null,null,null,null,-5.1,null,null,null,null,null,null],
    ["PP","NESINA","SAO JOAO",null,null,null,null,null,11.7,null,null,null,null,null,null],
    ["PP","DRAMIN","SAO JOAO",null,null,null,null,null,6.2,null,null,null,null,null,null],
    ["PP","RINOSORO","SAO JOAO",null,null,null,null,null,3.3,null,null,null,null,null,null],
    ["PP","LISADOR","SAO JOAO",null,null,null,null,null,23.3,null,null,null,null,null,null],
    ["PP","PREDSIM","SAO JOAO",null,null,null,null,null,2.5,null,null,null,null,null,null],
    ["PP","ALIVIUM","SAO JOAO",null,null,null,null,null,4.5,null,null,null,null,null,null],
    ["PP","COLFLEX","SAO JOAO",null,null,null,null,null,-1.2,null,null,null,null,null,null],
    ["PP","ADDERA D3","PANVEL",null,null,null,null,null,-1.1,null,null,null,null,null,null],
    ["PP","NESINA","PANVEL",null,null,null,null,null,10.4,null,null,null,null,null,null],
    ["PP","DRAMIN","PANVEL",null,null,null,null,null,-5.7,null,null,null,null,null,null],
    ["PP","RINOSORO","PANVEL",null,null,null,null,null,-14.6,null,null,null,null,null,null],
    ["PP","LISADOR","PANVEL",null,null,null,null,null,5,null,null,null,null,null,null],
    ["PP","PREDSIM","PANVEL",null,null,null,null,null,-9.7,null,null,null,null,null,null],
    ["PP","ALIVIUM","PANVEL",null,null,null,null,null,-19.9,null,null,null,null,null,null],
    ["PP","COLFLEX","PANVEL",null,null,null,null,null,-10.7,null,null,null,null,null,null],
    ["PP","ADDERA D3","PACHECO",null,null,null,null,null,-10.6,null,null,null,null,null,null],
    ["PP","NESINA","PACHECO",null,null,null,null,null,13,null,null,null,null,null,null],
    ["PP","DRAMIN","PACHECO",null,null,null,null,null,-18.9,null,null,null,null,null,null],
    ["PP","RINOSORO","PACHECO",null,null,null,null,null,-22.1,null,null,null,null,null,null],
    ["PP","LISADOR","PACHECO",null,null,null,null,null,8.4,null,null,null,null,null,null],
    ["PP","PREDSIM","PACHECO",null,null,null,null,null,-8.7,null,null,null,null,null,null],
    ["PP","ALIVIUM","PACHECO",null,null,null,null,null,-22.5,null,null,null,null,null,null],
    ["PP","COLFLEX","PACHECO",null,null,null,null,null,15.5,null,null,null,null,null,null],
    ["PP","ADDERA D3","DROGAL",null,null,null,null,null,16.2,null,null,null,null,null,null],
    ["PP","NESINA","DROGAL",null,null,null,null,null,12.2,null,null,null,null,null,null],
    ["PP","DRAMIN","DROGAL",null,null,null,null,null,9.8,null,null,null,null,null,null],
    ["PP","RINOSORO","DROGAL",null,null,null,null,null,-7.2,null,null,null,null,null,null],
    ["PP","LISADOR","DROGAL",null,null,null,null,null,14.9,null,null,null,null,null,null],
    ["PP","PREDSIM","DROGAL",null,null,null,null,null,-2.3,null,null,null,null,null,null],
    ["PP","ALIVIUM","DROGAL",null,null,null,null,null,-8.5,null,null,null,null,null,null],
    ["PP","COLFLEX","DROGAL",null,null,null,null,null,-1.2,null,null,null,null,null,null],
    ["PP","ADDERA D3","ARAUJO",null,null,null,null,null,-7.4,null,null,null,null,null,null],
    ["PP","NESINA","ARAUJO",null,null,null,null,null,5.2,null,null,null,null,null,null],
    ["PP","DRAMIN","ARAUJO",null,null,null,null,null,-7.5,null,null,null,null,null,null],
    ["PP","RINOSORO","ARAUJO",null,null,null,null,null,-12.5,null,null,null,null,null,null],
    ["PP","LISADOR","ARAUJO",null,null,null,null,null,11,null,null,null,null,null,null],
    ["PP","PREDSIM","ARAUJO",null,null,null,null,null,-17.6,null,null,null,null,null,null],
    ["PP","ALIVIUM","ARAUJO",null,null,null,null,null,-16.1,null,null,null,null,null,null],
    ["PP","COLFLEX","ARAUJO",null,null,null,null,null,-14.7,null,null,null,null,null,null],
    ["PP","ADDERA D3","VD",null,null,null,null,null,-1.5,null,null,null,null,null,null],
    ["PP","NESINA","VD",null,null,null,null,null,-4.1,null,null,null,null,null,null],
    ["PP","DRAMIN","VD",null,null,null,null,null,-3.8,null,null,null,null,null,null],
    ["PP","RINOSORO","VD",null,null,null,null,null,-16.9,null,null,null,null,null,null],
    ["PP","LISADOR","VD",null,null,null,null,null,7.6,null,null,null,null,null,null],
    ["PP","PREDSIM","VD",null,null,null,null,null,-12,null,null,null,null,null,null],
    ["PP","ALIVIUM","VD",null,null,null,null,null,-15.3,null,null,null,null,null,null],
    ["PP","COLFLEX","VD",null,null,null,null,null,9,null,null,null,null,null,null],
    ["PP","ADDERA D3","VI",null,null,null,null,null,20.3,null,null,null,null,null,null],
    ["PP","NESINA","VI",null,null,null,null,null,18,null,null,null,null,null,null],
    ["PP","DRAMIN","VI",null,null,null,null,null,11.6,null,null,null,null,null,null],
    ["PP","RINOSORO","VI",null,null,null,null,null,-11.5,null,null,null,null,null,null],
    ["PP","LISADOR","VI",null,null,null,null,null,28.7,null,null,null,null,null,null],
    ["PP","PREDSIM","VI",null,null,null,null,null,-4.6,null,null,null,null,null,null],
    ["PP","ALIVIUM","VI",null,null,null,null,null,-7.9,null,null,null,null,null,null],
    ["PP","COLFLEX","VI",null,null,null,null,null,-16.7,null,null,null,null,null,null],
    ["SC","EPISOL","DROGASIL",null,null,null,null,null,-14,null,null,null,null,null,null],
    ["SC","EPIDRAT","DROGASIL",null,null,null,null,null,-7.3,null,null,null,null,null,null],
    ["SC","IVY C","DROGASIL",null,null,null,null,null,-24,null,null,null,null,null,null],
    ["SC","HYDRAPORIN","DROGASIL",null,null,null,null,null,-32.5,null,null,null,null,null,null],
    ["SC","GLYCARE","DROGASIL",null,null,null,null,null,-5.9,null,null,null,null,null,null],
    ["SC","PIELUS FORTE","DROGASIL",null,null,null,null,null,73.2,null,null,null,null,null,null],
    ["SC","NOUVE","DROGASIL",null,null,null,null,null,-15.6,null,null,null,null,null,null],
    ["SC","DIPROSALIC","DROGASIL",null,null,null,null,null,2.7,null,null,null,null,null,null],
    ["SC","EPISOL","DELIVERY",null,null,null,null,null,84.8,null,null,null,null,null,null],
    ["SC","EPIDRAT","DELIVERY",null,null,null,null,null,28.5,null,null,null,null,null,null],
    ["SC","IVY C","DELIVERY",null,null,null,null,null,20.2,null,null,null,null,null,null],
    ["SC","HYDRAPORIN","DELIVERY",null,null,null,null,null,-11,null,null,null,null,null,null],
    ["SC","GLYCARE","DELIVERY",null,null,null,null,null,43.7,null,null,null,null,null,null],
    ["SC","PIELUS FORTE","DELIVERY",null,null,null,null,null,164.8,null,null,null,null,null,null],
    ["SC","NOUVE","DELIVERY",null,null,null,null,null,62.3,null,null,null,null,null,null],
    ["SC","DIPROSALIC","DELIVERY",null,null,null,null,null,26.2,null,null,null,null,null,null],
    ["SC","EPISOL","PAGUE MENOS",null,null,null,null,null,12.9,null,null,null,null,null,null],
    ["SC","EPIDRAT","PAGUE MENOS",null,null,null,null,null,48.1,null,null,null,null,null,null],
    ["SC","IVY C","PAGUE MENOS",null,null,null,null,null,11.5,null,null,null,null,null,null],
    ["SC","HYDRAPORIN","PAGUE MENOS",null,null,null,null,null,9.9,null,null,null,null,null,null],
    ["SC","GLYCARE","PAGUE MENOS",null,null,null,null,null,14.4,null,null,null,null,null,null],
    ["SC","PIELUS FORTE","PAGUE MENOS",null,null,null,null,null,129.2,null,null,null,null,null,null],
    ["SC","NOUVE","PAGUE MENOS",null,null,null,null,null,25.8,null,null,null,null,null,null],
    ["SC","DIPROSALIC","PAGUE MENOS",null,null,null,null,null,7,null,null,null,null,null,null],
    ["SC","EPISOL","DROGARIA SAO PAULO",null,null,null,null,null,2,null,null,null,null,null,null],
    ["SC","EPIDRAT","DROGARIA SAO PAULO",null,null,null,null,null,-4.2,null,null,null,null,null,null],
    ["SC","IVY C","DROGARIA SAO PAULO",null,null,null,null,null,2.4,null,null,null,null,null,null],
    ["SC","HYDRAPORIN","DROGARIA SAO PAULO",null,null,null,null,null,-18,null,null,null,null,null,null],
    ["SC","GLYCARE","DROGARIA SAO PAULO",null,null,null,null,null,-3.8,null,null,null,null,null,null],
    ["SC","PIELUS FORTE","DROGARIA SAO PAULO",null,null,null,null,null,124.4,null,null,null,null,null,null],
    ["SC","NOUVE","DROGARIA SAO PAULO",null,null,null,null,null,12.1,null,null,null,null,null,null],
    ["SC","DIPROSALIC","DROGARIA SAO PAULO",null,null,null,null,null,9.5,null,null,null,null,null,null],
    ["SC","EPISOL","RAIA",null,null,null,null,null,-19.4,null,null,null,null,null,null],
    ["SC","EPIDRAT","RAIA",null,null,null,null,null,-17.3,null,null,null,null,null,null],
    ["SC","IVY C","RAIA",null,null,null,null,null,-24.4,null,null,null,null,null,null],
    ["SC","HYDRAPORIN","RAIA",null,null,null,null,null,-38.3,null,null,null,null,null,null],
    ["SC","GLYCARE","RAIA",null,null,null,null,null,-13.2,null,null,null,null,null,null],
    ["SC","PIELUS FORTE","RAIA",null,null,null,null,null,49.1,null,null,null,null,null,null],
    ["SC","NOUVE","RAIA",null,null,null,null,null,-21.9,null,null,null,null,null,null],
    ["SC","DIPROSALIC","RAIA",null,null,null,null,null,-2.9,null,null,null,null,null,null],
    ["SC","EPISOL","SAO JOAO",null,null,null,null,null,10.6,null,null,null,null,null,null],
    ["SC","EPIDRAT","SAO JOAO",null,null,null,null,null,40.4,null,null,null,null,null,null],
    ["SC","IVY C","SAO JOAO",null,null,null,null,null,-32,null,null,null,null,null,null],
    ["SC","HYDRAPORIN","SAO JOAO",null,null,null,null,null,7.8,null,null,null,null,null,null],
    ["SC","GLYCARE","SAO JOAO",null,null,null,null,null,176.6,null,null,null,null,null,null],
    ["SC","PIELUS FORTE","SAO JOAO",null,null,null,null,null,71.1,null,null,null,null,null,null],
    ["SC","NOUVE","SAO JOAO",null,null,null,null,null,22.6,null,null,null,null,null,null],
    ["SC","DIPROSALIC","SAO JOAO",null,null,null,null,null,26.7,null,null,null,null,null,null],
    ["SC","EPISOL","PANVEL",null,null,null,null,null,7.7,null,null,null,null,null,null],
    ["SC","EPIDRAT","PANVEL",null,null,null,null,null,-7.1,null,null,null,null,null,null],
    ["SC","IVY C","PANVEL",null,null,null,null,null,-17.4,null,null,null,null,null,null],
    ["SC","HYDRAPORIN","PANVEL",null,null,null,null,null,-43.4,null,null,null,null,null,null],
    ["SC","GLYCARE","PANVEL",null,null,null,null,null,18.9,null,null,null,null,null,null],
    ["SC","PIELUS FORTE","PANVEL",null,null,null,null,null,134.7,null,null,null,null,null,null],
    ["SC","NOUVE","PANVEL",null,null,null,null,null,3.7,null,null,null,null,null,null],
    ["SC","DIPROSALIC","PANVEL",null,null,null,null,null,29.6,null,null,null,null,null,null],
    ["SC","EPISOL","PACHECO",null,null,null,null,null,-14.7,null,null,null,null,null,null],
    ["SC","EPIDRAT","PACHECO",null,null,null,null,null,-11.1,null,null,null,null,null,null],
    ["SC","IVY C","PACHECO",null,null,null,null,null,-15.3,null,null,null,null,null,null],
    ["SC","HYDRAPORIN","PACHECO",null,null,null,null,null,-24.9,null,null,null,null,null,null],
    ["SC","GLYCARE","PACHECO",null,null,null,null,null,-4.3,null,null,null,null,null,null],
    ["SC","PIELUS FORTE","PACHECO",null,null,null,null,null,82.9,null,null,null,null,null,null],
    ["SC","NOUVE","PACHECO",null,null,null,null,null,-5.2,null,null,null,null,null,null],
    ["SC","DIPROSALIC","PACHECO",null,null,null,null,null,6.8,null,null,null,null,null,null],
    ["SC","EPISOL","DROGAL",null,null,null,null,null,-22.8,null,null,null,null,null,null],
    ["SC","EPIDRAT","DROGAL",null,null,null,null,null,41,null,null,null,null,null,null],
    ["SC","IVY C","DROGAL",null,null,null,null,null,-22.5,null,null,null,null,null,null],
    ["SC","HYDRAPORIN","DROGAL",null,null,null,null,null,30.6,null,null,null,null,null,null],
    ["SC","GLYCARE","DROGAL",null,null,null,null,null,55.6,null,null,null,null,null,null],
    ["SC","PIELUS FORTE","DROGAL",null,null,null,null,null,909.9,null,null,null,null,null,null],
    ["SC","NOUVE","DROGAL",null,null,null,null,null,74.5,null,null,null,null,null,null],
    ["SC","DIPROSALIC","DROGAL",null,null,null,null,null,155.3,null,null,null,null,null,null],
    ["SC","EPISOL","ARAUJO",null,null,null,null,null,3,null,null,null,null,null,null],
    ["SC","EPIDRAT","ARAUJO",null,null,null,null,null,1,null,null,null,null,null,null],
    ["SC","IVY C","ARAUJO",null,null,null,null,null,17.3,null,null,null,null,null,null],
    ["SC","HYDRAPORIN","ARAUJO",null,null,null,null,null,-33.4,null,null,null,null,null,null],
    ["SC","GLYCARE","ARAUJO",null,null,null,null,null,50.6,null,null,null,null,null,null],
    ["SC","PIELUS FORTE","ARAUJO",null,null,null,null,null,101.2,null,null,null,null,null,null],
    ["SC","NOUVE","ARAUJO",null,null,null,null,null,-21.7,null,null,null,null,null,null],
    ["SC","DIPROSALIC","ARAUJO",null,null,null,null,null,6.4,null,null,null,null,null,null],
    ["SC","EPISOL","VD",null,null,null,null,null,14.7,null,null,null,null,null,null],
    ["SC","EPIDRAT","VD",null,null,null,null,null,12.5,null,null,null,null,null,null],
    ["SC","IVY C","VD",null,null,null,null,null,1.3,null,null,null,null,null,null],
    ["SC","HYDRAPORIN","VD",null,null,null,null,null,-16,null,null,null,null,null,null],
    ["SC","GLYCARE","VD",null,null,null,null,null,14,null,null,null,null,null,null],
    ["SC","PIELUS FORTE","VD",null,null,null,null,null,123.5,null,null,null,null,null,null],
    ["SC","NOUVE","VD",null,null,null,null,null,25.7,null,null,null,null,null,null],
    ["SC","DIPROSALIC","VD",null,null,null,null,null,12.8,null,null,null,null,null,null],
    ["SC","EPISOL","VI",null,null,null,null,null,7.2,null,null,null,null,null,null],
    ["SC","EPIDRAT","VI",null,null,null,null,null,35.9,null,null,null,null,null,null],
    ["SC","IVY C","VI",null,null,null,null,null,7.2,null,null,null,null,null,null],
    ["SC","HYDRAPORIN","VI",null,null,null,null,null,8.6,null,null,null,null,null,null],
    ["SC","GLYCARE","VI",null,null,null,null,null,9.3,null,null,null,null,null,null],
    ["SC","PIELUS FORTE","VI",null,null,null,null,null,341.8,null,null,null,null,null,null],
    ["SC","NOUVE","VI",null,null,null,null,null,17.3,null,null,null,null,null,null],
    ["SC","DIPROSALIC","VI",null,null,null,null,null,22.8,null,null,null,null,null,null],
    ["SG","TORSILAX","DROGASIL",null,null,null,null,null,31.8,null,null,null,null,null,null],
    ["SG","NEOSORO","DROGASIL",null,null,null,null,null,0.4,null,null,null,null,null,null],
    ["SG","DIPIRONA SODICA MG","DROGASIL",null,null,null,null,null,11.4,null,null,null,null,null,null],
    ["SG","NIST+OXID.ZINCO MG","DROGASIL",null,null,null,null,null,22.7,null,null,null,null,null,null],
    ["SG","FLAVONID","DROGASIL",null,null,null,null,null,112.6,null,null,null,null,null,null],
    ["SG","LOSARTAN POTAS.MG","DROGASIL",null,null,null,null,null,8.2,null,null,null,null,null,null],
    ["SG","DORALGINA","DROGASIL",null,null,null,null,null,0.1,null,null,null,null,null,null],
    ["SG","VIT NEO QUIMICA","DROGASIL",null,null,null,null,null,27.2,null,null,null,null,null,null],
    ["SG","HISTAMIN","DROGASIL",null,null,null,null,null,0.8,null,null,null,null,null,null],
    ["SG","TORSILAX","DELIVERY",null,null,null,null,null,101.3,null,null,null,null,null,null],
    ["SG","NEOSORO","DELIVERY",null,null,null,null,null,-11.5,null,null,null,null,null,null],
    ["SG","DIPIRONA SODICA MG","DELIVERY",null,null,null,null,null,-10.9,null,null,null,null,null,null],
    ["SG","NIST+OXID.ZINCO MG","DELIVERY",null,null,null,null,null,43.6,null,null,null,null,null,null],
    ["SG","FLAVONID","DELIVERY",null,null,null,null,null,751.2,null,null,null,null,null,null],
    ["SG","LOSARTAN POTAS.MG","DELIVERY",null,null,null,null,null,-87.1,null,null,null,null,null,null],
    ["SG","DORALGINA","DELIVERY",null,null,null,null,null,-52.9,null,null,null,null,null,null],
    ["SG","VIT NEO QUIMICA","DELIVERY",null,null,null,null,null,164.2,null,null,null,null,null,null],
    ["SG","HISTAMIN","DELIVERY",null,null,null,null,null,-7.9,null,null,null,null,null,null],
    ["SG","TORSILAX","PAGUE MENOS",null,null,null,null,null,-6.6,null,null,null,null,null,null],
    ["SG","NEOSORO","PAGUE MENOS",null,null,null,null,null,-12.6,null,null,null,null,null,null],
    ["SG","DIPIRONA SODICA MG","PAGUE MENOS",null,null,null,null,null,90.4,null,null,null,null,null,null],
    ["SG","NIST+OXID.ZINCO MG","PAGUE MENOS",null,null,null,null,null,58.1,null,null,null,null,null,null],
    ["SG","FLAVONID","PAGUE MENOS",null,null,null,null,null,-10.5,null,null,null,null,null,null],
    ["SG","LOSARTAN POTAS.MG","PAGUE MENOS",null,null,null,null,null,65.7,null,null,null,null,null,null],
    ["SG","DORALGINA","PAGUE MENOS",null,null,null,null,null,-26.8,null,null,null,null,null,null],
    ["SG","VIT NEO QUIMICA","PAGUE MENOS",null,null,null,null,null,57.4,null,null,null,null,null,null],
    ["SG","HISTAMIN","PAGUE MENOS",null,null,null,null,null,-8,null,null,null,null,null,null],
    ["SG","TORSILAX","DROGARIA SAO PAULO",null,null,null,null,null,-7.3,null,null,null,null,null,null],
    ["SG","NEOSORO","DROGARIA SAO PAULO",null,null,null,null,null,12.9,null,null,null,null,null,null],
    ["SG","DIPIRONA SODICA MG","DROGARIA SAO PAULO",null,null,null,null,null,19.7,null,null,null,null,null,null],
    ["SG","NIST+OXID.ZINCO MG","DROGARIA SAO PAULO",null,null,null,null,null,75.7,null,null,null,null,null,null],
    ["SG","FLAVONID","DROGARIA SAO PAULO",null,null,null,null,null,6.8,null,null,null,null,null,null],
    ["SG","LOSARTAN POTAS.MG","DROGARIA SAO PAULO",null,null,null,null,null,-95.5,null,null,null,null,null,null],
    ["SG","DORALGINA","DROGARIA SAO PAULO",null,null,null,null,null,-16.6,null,null,null,null,null,null],
    ["SG","VIT NEO QUIMICA","DROGARIA SAO PAULO",null,null,null,null,null,32.9,null,null,null,null,null,null],
    ["SG","HISTAMIN","DROGARIA SAO PAULO",null,null,null,null,null,-21.1,null,null,null,null,null,null],
    ["SG","TORSILAX","RAIA",null,null,null,null,null,20.5,null,null,null,null,null,null],
    ["SG","NEOSORO","RAIA",null,null,null,null,null,-8.2,null,null,null,null,null,null],
    ["SG","DIPIRONA SODICA MG","RAIA",null,null,null,null,null,-0.1,null,null,null,null,null,null],
    ["SG","NIST+OXID.ZINCO MG","RAIA",null,null,null,null,null,5.9,null,null,null,null,null,null],
    ["SG","FLAVONID","RAIA",null,null,null,null,null,121,null,null,null,null,null,null],
    ["SG","LOSARTAN POTAS.MG","RAIA",null,null,null,null,null,-4.9,null,null,null,null,null,null],
    ["SG","DORALGINA","RAIA",null,null,null,null,null,-14.3,null,null,null,null,null,null],
    ["SG","VIT NEO QUIMICA","RAIA",null,null,null,null,null,39.1,null,null,null,null,null,null],
    ["SG","HISTAMIN","RAIA",null,null,null,null,null,-6.5,null,null,null,null,null,null],
    ["SG","TORSILAX","SAO JOAO",null,null,null,null,null,27.4,null,null,null,null,null,null],
    ["SG","NEOSORO","SAO JOAO",null,null,null,null,null,-20.9,null,null,null,null,null,null],
    ["SG","DIPIRONA SODICA MG","SAO JOAO",null,null,null,null,null,216.8,null,null,null,null,null,null],
    ["SG","NIST+OXID.ZINCO MG","SAO JOAO",null,null,null,null,null,35816.8,null,null,null,null,null,null],
    ["SG","FLAVONID","SAO JOAO",null,null,null,null,null,1037,null,null,null,null,null,null],
    ["SG","LOSARTAN POTAS.MG","SAO JOAO",null,null,null,null,null,-28.4,null,null,null,null,null,null],
    ["SG","DORALGINA","SAO JOAO",null,null,null,null,null,21,null,null,null,null,null,null],
    ["SG","VIT NEO QUIMICA","SAO JOAO",null,null,null,null,null,52.5,null,null,null,null,null,null],
    ["SG","HISTAMIN","SAO JOAO",null,null,null,null,null,-1.3,null,null,null,null,null,null],
    ["SG","TORSILAX","PANVEL",null,null,null,null,null,20.2,null,null,null,null,null,null],
    ["SG","NEOSORO","PANVEL",null,null,null,null,null,-11.4,null,null,null,null,null,null],
    ["SG","DIPIRONA SODICA MG","PANVEL",null,null,null,null,null,-15.8,null,null,null,null,null,null],
    ["SG","NIST+OXID.ZINCO MG","PANVEL",null,null,null,null,null,40.7,null,null,null,null,null,null],
    ["SG","FLAVONID","PANVEL",null,null,null,null,null,63.4,null,null,null,null,null,null],
    ["SG","LOSARTAN POTAS.MG","PANVEL",null,null,null,null,null,105.9,null,null,null,null,null,null],
    ["SG","DORALGINA","PANVEL",null,null,null,null,null,-22.3,null,null,null,null,null,null],
    ["SG","VIT NEO QUIMICA","PANVEL",null,null,null,null,null,70.8,null,null,null,null,null,null],
    ["SG","HISTAMIN","PANVEL",null,null,null,null,null,31.5,null,null,null,null,null,null],
    ["SG","TORSILAX","PACHECO",null,null,null,null,null,-7.2,null,null,null,null,null,null],
    ["SG","NEOSORO","PACHECO",null,null,null,null,null,-2,null,null,null,null,null,null],
    ["SG","DIPIRONA SODICA MG","PACHECO",null,null,null,null,null,281.4,null,null,null,null,null,null],
    ["SG","NIST+OXID.ZINCO MG","PACHECO",null,null,null,null,null,34.6,null,null,null,null,null,null],
    ["SG","FLAVONID","PACHECO",null,null,null,null,null,-24.9,null,null,null,null,null,null],
    ["SG","LOSARTAN POTAS.MG","PACHECO",null,null,null,null,null,-94.7,null,null,null,null,null,null],
    ["SG","DORALGINA","PACHECO",null,null,null,null,null,0.5,null,null,null,null,null,null],
    ["SG","VIT NEO QUIMICA","PACHECO",null,null,null,null,null,12,null,null,null,null,null,null],
    ["SG","HISTAMIN","PACHECO",null,null,null,null,null,-30.4,null,null,null,null,null,null],
    ["SG","TORSILAX","DROGAL",null,null,null,null,null,33.8,null,null,null,null,null,null],
    ["SG","NEOSORO","DROGAL",null,null,null,null,null,7.5,null,null,null,null,null,null],
    ["SG","DIPIRONA SODICA MG","DROGAL",null,null,null,null,null,157.3,null,null,null,null,null,null],
    ["SG","NIST+OXID.ZINCO MG","DROGAL",null,null,null,null,null,-26.2,null,null,null,null,null,null],
    ["SG","FLAVONID","DROGAL",null,null,null,null,null,83.6,null,null,null,null,null,null],
    ["SG","LOSARTAN POTAS.MG","DROGAL",null,null,null,null,null,31.3,null,null,null,null,null,null],
    ["SG","DORALGINA","DROGAL",null,null,null,null,null,21.4,null,null,null,null,null,null],
    ["SG","VIT NEO QUIMICA","DROGAL",null,null,null,null,null,77.6,null,null,null,null,null,null],
    ["SG","HISTAMIN","DROGAL",null,null,null,null,null,11.2,null,null,null,null,null,null],
    ["SG","TORSILAX","ARAUJO",null,null,null,null,null,2.4,null,null,null,null,null,null],
    ["SG","NEOSORO","ARAUJO",null,null,null,null,null,-0.6,null,null,null,null,null,null],
    ["SG","DIPIRONA SODICA MG","ARAUJO",null,null,null,null,null,25,null,null,null,null,null,null],
    ["SG","NIST+OXID.ZINCO MG","ARAUJO",null,null,null,null,null,25.7,null,null,null,null,null,null],
    ["SG","FLAVONID","ARAUJO",null,null,null,null,null,151.4,null,null,null,null,null,null],
    ["SG","LOSARTAN POTAS.MG","ARAUJO",null,null,null,null,null,27.5,null,null,null,null,null,null],
    ["SG","DORALGINA","ARAUJO",null,null,null,null,null,-6.2,null,null,null,null,null,null],
    ["SG","VIT NEO QUIMICA","ARAUJO",null,null,null,null,null,-7.1,null,null,null,null,null,null],
    ["SG","HISTAMIN","ARAUJO",null,null,null,null,null,2,null,null,null,null,null,null],
    ["SG","TORSILAX","VD",null,null,null,null,null,19.3,null,null,null,null,null,null],
    ["SG","NEOSORO","VD",null,null,null,null,null,-3.2,null,null,null,null,null,null],
    ["SG","DIPIRONA SODICA MG","VD",null,null,null,null,null,10,null,null,null,null,null,null],
    ["SG","NIST+OXID.ZINCO MG","VD",null,null,null,null,null,29.2,null,null,null,null,null,null],
    ["SG","FLAVONID","VD",null,null,null,null,null,85.9,null,null,null,null,null,null],
    ["SG","LOSARTAN POTAS.MG","VD",null,null,null,null,null,-13.2,null,null,null,null,null,null],
    ["SG","DORALGINA","VD",null,null,null,null,null,-3.2,null,null,null,null,null,null],
    ["SG","VIT NEO QUIMICA","VD",null,null,null,null,null,47.5,null,null,null,null,null,null],
    ["SG","HISTAMIN","VD",null,null,null,null,null,-2.9,null,null,null,null,null,null],
    ["SG","TORSILAX","VI",null,null,null,null,null,2.3,null,null,null,null,null,null],
    ["SG","NEOSORO","VI",null,null,null,null,null,-15.6,null,null,null,null,null,null],
    ["SG","DIPIRONA SODICA MG","VI",null,null,null,null,null,65.8,null,null,null,null,null,null],
    ["SG","NIST+OXID.ZINCO MG","VI",null,null,null,null,null,15.4,null,null,null,null,null,null],
    ["SG","FLAVONID","VI",null,null,null,null,null,0.1,null,null,null,null,null,null],
    ["SG","LOSARTAN POTAS.MG","VI",null,null,null,null,null,9.5,null,null,null,null,null,null],
    ["SG","DORALGINA","VI",null,null,null,null,null,9.4,null,null,null,null,null,null],
    ["SG","VIT NEO QUIMICA","VI",null,null,null,null,null,-21.1,null,null,null,null,null,null],
    ["SG","HISTAMIN","VI",null,null,null,null,null,-0.7,null,null,null,null,null,null],
    ["VITNQ","VIT NEO QUIMICA N_Q","TOTAL",8.7,4.2,8.9,null,null,2.5,null,null,2.2,null,null,null],
    ["VITNQ","VITAMINA D3 N_Q","TOTAL",4.1,2.3,4.9,null,null,20.5,null,null,20.6,null,null,null],
    ["VITNQ","VITAMINA B1 N_Q","TOTAL",0,0,0,null,null,-25.5,null,null,-18.2,null,null,null],
    ["VITNQ","Total","TOTAL",12.8,6.6,13.8,null,null,8.1,null,null,8,null,null,null],
    ["VITNQ","TOTAL","DROGASIL",0.8,0.7,1.3,null,null,62.4,null,null,54.1,null,null,null],
    ["VITNQ","TOTAL","PAGUE MENOS",0.6,0.5,1,null,null,57.4,null,null,48.9,null,null,null],
    ["VITNQ","TOTAL","DELIVERY",0.3,0.5,0.9,null,null,205.9,null,null,214.5,null,null,null],
    ["VITNQ","TOTAL","PANVEL",0.3,0.4,0.7,null,null,127.2,null,null,117.4,null,null,null],
    ["VITNQ","TOTAL","RAIA",0.3,0.3,0.5,null,null,74.1,null,null,65.1,null,null,null],
    ["VITNQ","TOTAL","DROGARIA SAO PAULO",0.4,0.3,0.5,null,null,37.8,null,null,31.3,null,null,null],
    ["VITNQ","TOTAL","CATARINENSE",0.2,0.1,0.3,null,null,64.7,null,null,84.1,null,null,null],
    ["VITNQ","TOTAL","ARAUJO",0.3,0.2,0.3,null,null,-1.3,null,null,-6.1,null,null,null],
    ["VITNQ","TOTAL","PACHECO",0.2,0.1,0.3,null,null,20.7,null,null,15.2,null,null,null],
    ["VITNQ","TOTAL","DROGAL",0.2,0.1,0.2,null,null,42.1,null,null,55.4,null,null,null],
    ["VITNQ","TOTAL","OUTROS",0.4,0.3,0.6,null,null,37.4,null,null,39.4,null,null,null],
    ["VITNQ","TOTAL","VD",4,3.3,6.6,null,null,65.6,null,null,62.1,null,null,null],
    ["VITNQ","TOTAL","VI",8.8,3.2,7.3,null,null,-18.6,null,null,-17.1,null,null,null],
    ["VITNQ","TOTAL","TOTAL",12.8,6.6,13.8,null,null,8.1,null,null,8,null,null,null],
    ["CH","BUSCOPAN","TOTAL",33.7,16.4,35.5,null,null,2.1,33.7,66.3,5.6,null,null,null],
    ["CH","BENEGRIP","TOTAL",28.3,13.2,29.3,null,null,-1.6,54.6,45.4,3.8,null,null,null],
    ["CH","NEOSALDINA","TOTAL",24.6,11.3,25.2,null,null,-3.4,44.8,55.2,2.4,null,null,null],
    ["CH","TAMARINE","TOTAL",12.6,6.6,14.6,null,null,9.6,52.6,47.4,15.6,null,null,null],
    ["CH","EPOCLER","TOTAL",12.2,5.9,13.3,null,null,1.7,47,53,8.9,null,null,null],
    ["CH","DEMAIS","TOTAL",105.2,45.2,102.1,null,null,null,45.5,54.5,-2.9,null,null,null],
    ["PP","ADDERA D3","TOTAL",35.5,17.9,36.9,null,null,5.6,71.5,28.5,3.9,null,null,null],
    ["PP","NESINA","TOTAL",31.1,15.5,32.6,null,null,5,53,47,5.1,null,null,null],
    ["PP","DRAMIN","TOTAL",17.7,8.5,18.6,null,null,0.7,35.7,64.3,5.5,null,null,null],
    ["PP","RINOSORO","TOTAL",16,6.5,13.6,null,null,-14.2,69.5,30.5,-15.3,null,null,null],
    ["PP","LISADOR","TOTAL",10.3,5.6,12.1,null,null,13.7,49.5,50.5,17.3,null,null,null],
    ["PP","DEMAIS","TOTAL",143.3,74,156.7,null,null,null,56.9,43.1,9.4,null,null,null],
    ["SC","EPISOL","TOTAL",17.9,9.8,20.2,null,null,15,83.3,16.7,13.4,null,null,null],
    ["SC","EPIDRAT","TOTAL",14.6,8.1,16.9,null,null,17.1,85.6,14.4,15.4,null,null,null],
    ["SC","IVY C","TOTAL",3.5,1.7,3.6,null,null,1.1,87.8,12.2,2,null,null,null],
    ["SC","HYDRAPORIN","TOTAL",3.9,1.6,3.4,null,null,-11.4,81,19,-12.2,null,null,null],
    ["SC","GLYCARE","TOTAL",2.4,1.3,2.8,null,null,14.7,89.7,10.3,13.5,null,null,null],
    ["SC","DEMAIS","TOTAL",19.4,11.9,24.8,null,null,null,80.3,19.7,27.8,null,null,null],
    ["SG","TORSILAX","TOTAL",25.2,12.1,26.5,null,null,1,19.8,80.2,5.3,null,null,null],
    ["SG","NEOSORO","TOTAL",21.3,8.7,18.7,null,null,-14.1,29.1,70.9,-12.4,null,null,null],
    ["SG","DIPIRONA SODICA MG","TOTAL",12.6,8.5,18.3,null,null,42.6,27.1,72.9,45.8,null,null,null],
    ["SG","NIST+OXID.ZINCO MG","TOTAL",12.4,6.5,14.6,null,null,10.7,16.3,83.7,17.4,null,null,null],
    ["SG","FLAVONID","TOTAL",8.4,4.8,10.4,null,null,20.1,40.6,59.4,23.2,null,null,null],
    ["SG","DEMAIS","TOTAL",146.8,75.3,162.5,null,null,null,27.7,72.3,10.7,null,null,null]
  ]
};

/* Resolução da base, em ordem de precedência:
 *   1. ?data=AAAA-MM-DD na URL  -> a base daquele dia (armazenamento local, ou o arquivo
 *      base-boletim-AAAA-MM-DD.js do repositório)
 *   2. a última base publicada pelo Atualizador neste navegador
 *   3. a base do arquivo acima, que é a versão do repositório
 * BOLETIM_LIMPAR_BASE_LOCAL() apaga o que foi publicado localmente. */
(function () {
  var RAIZ = 'boletim.base.v1';
  var valida = function (b) {
    return b && b.META && b.COLUNAS && b.COLUNAS.length && b.FATOS && b.FATOS.length;
  };
  var ler = function (chave) {
    try { return JSON.parse(localStorage.getItem(chave) || 'null'); } catch (e) { return null; }
  };
  window.BOLETIM_LIMPAR_BASE_LOCAL = function () {
    try {
      var fora = [];
      for (var i = localStorage.length - 1; i >= 0; i--) {
        var k = localStorage.key(i);
        if (k && k.indexOf(RAIZ) === 0) { fora.push(k); localStorage.removeItem(k); }
      }
      return fora.length + ' base(s) local(is) removida(s). Recarregue a página.';
    } catch (e) { return 'Armazenamento indisponível.'; }
  };
  window.BOLETIM_DATAS_LOCAIS = function () {
    var out = [];
    try {
      for (var i = 0; i < localStorage.length; i++) {
        var k = localStorage.key(i);
        if (k && k.indexOf(RAIZ + '.') === 0) out.push(k.slice(RAIZ.length + 1));
      }
    } catch (e) {}
    return out.sort().reverse();
  };

  var data = null;
  try {
    var m = /[?&]data=(\d{4}-\d{2}-\d{2})/.exec(window.location.search || '');
    if (m) data = m[1];
  } catch (e) {}

  var escolhida = null;
  if (data) {
    escolhida = ler(RAIZ + '.' + data);
    if (!valida(escolhida)) {
      // arquivo do dia versionado no repositório
      try {
        var req = new XMLHttpRequest();
        req.open('GET', 'base-boletim-' + data + '.js', false);
        req.send(null);
        if (req.status === 200 || req.status === 0) {
          var guarda = window.BASE_BOLETIM;
          new Function(req.responseText).call(window);
          if (valida(window.BASE_BOLETIM) && window.BASE_BOLETIM !== guarda) {
            escolhida = window.BASE_BOLETIM;
            window.BASE_BOLETIM = guarda;
          }
        }
      } catch (e) { /* arquivo do dia ausente — cai para a base do repositório */ }
    }
    if (!valida(escolhida)) window.BASE_BOLETIM_DATA_AUSENTE = data;
  }
  if (!valida(escolhida)) escolhida = ler(RAIZ);

  if (valida(escolhida)) {
    window.BASE_BOLETIM = escolhida;
    window.BASE_BOLETIM_LOCAL = true;
    window.BASE_BOLETIM_DATA = data || null;
  }
})();
